service: podly-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    STAGE: ${self:provider.stage}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    TAVILY_API_KEY: ${env:TAVILY_API_KEY}
  
  httpApi:
    cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
  serverless-offline:
    httpPort: 3000
    reloadHandler: true

functions:          
  createScript:
    handler: src/handlers/script.createScript
    events:
      - httpApi:
          path: /script/create
          method: post

  # 音声プレビューAPI
  previewAudio:
    handler: src/handlers/audio.previewAudio
    events:
      - httpApi:
          path: /audio/preview
          method: post 