service: podly-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    STAGE: ${self:provider.stage}
  
  httpApi:
    cors: true

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
  serverless-offline:
    httpPort: 3000
    reloadHandler: true

functions:
  hello:
    handler: src/handlers/hello.handler
    events:
      - httpApi:
          path: /hello
          method: get
  
  createPodcast:
    handler: src/handlers/podcast.createPodcast
    events:
      - httpApi:
          path: /podcasts
          method: post
          
  getPodcast:
    handler: src/handlers/podcast.getPodcast
    events:
      - httpApi:
          path: /podcasts/{id}
          method: get
          
  listPodcasts:
    handler: src/handlers/podcast.listPodcasts
    events:
      - httpApi:
          path: /podcasts
          method: get
          
  createScript:
    handler: src/handlers/script.createScript
    events:
      - httpApi:
          path: /script/create
          method: post 