service: podly-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30
  environment:
    NODE_ENV: ${self:provider.stage}
    STAGE: ${self:provider.stage}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    TAVILY_API_KEY: ${env:TAVILY_API_KEY}
    # 環境別のffmpeg/ffprobeパス設定
    FFMPEG_PATH: ${self:custom.ffmpegPath.${self:provider.stage}}
    FFPROBE_PATH: ${self:custom.ffprobePath.${self:provider.stage}}
  
  httpApi:
    cors: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  # 環境別のffmpegパス設定
  ffmpegPath:
    dev: ${env:FFMPEG_PATH, ''}  # ローカル環境では.envのFFMPEG_PATHを使用
    prod: /opt/bin/ffmpeg  # 本番環境ではLayerのffmpegを使用
  ffprobePath:
    dev: ${env:FFPROBE_PATH, ''}  # ローカル環境では.envのFFPROBE_PATHを使用
    prod: /opt/bin/ffprobe  # 本番環境ではLayerのffprobeを使用
  
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
  serverless-offline:
    httpPort: 3000
    reloadHandler: true

functions:          
  createScript:
    handler: src/handlers/script.createScript
    events:
      - httpApi:
          path: /script/create
          method: post

  # 音声プレビューAPI
  previewAudio:
    handler: src/handlers/audio.previewAudio
    environment:
      FFMPEG_PATH: ${self:custom.ffmpegPath.${self:provider.stage}}
      FFPROBE_PATH: ${self:custom.ffprobePath.${self:provider.stage}}
    events:
      - httpApi:
          path: /audio/preview
          method: post 